name: Publish documentation site
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/*.yml'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses:  actions/checkout@v2
      - name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: pacoorozco/probind
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: npm ci && npm run docs:build
          BUILD_DIR: docs/.vuepress/dist/
          CNAME: probind.pacoorozco.info
